name       : zip
version    : '3.0'
release    : 3
source     :
    - https://netix.dl.sourceforge.net/project/infozip/Zip%203.x%20%28latest%29/3.0/zip30.tar.gz : f0e8bb1f9b7eb0b01285495a2699df3a4b766784c1765a8f1aeedf63c0806369
license    : Info-ZIP
component  : system.base
summary    : Archiver for .zip files
description: |
    This is InfoZIP's zip program. It produces files that are fully compatible with the popular PKZIP program; however, the command line options are not identical. In other words, the end result is the same, but the methods differ.
builddeps  :
    - bzip2-devel
build      : |
    %make -f unix/Makefile generic_gcc
install    : |
    for bin in zip zipcloak zipnote zipsplit; do
        install -Dm00755 $bin $installdir/usr/bin/$bin
    done
